# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
user = User.create!(first_name: 'Com', last_name: 'Pyutierre', department: 'MMM', rank: 'Assistant Instructor', contact_number: '9123456789', email: 'mail1@example.com', password: "password")
researcher = user.create_researcher!()
researcher.proposals.create!(title: 'Fire Resistant Paper', researcher: 'Com Pyutierre', coresearchers: 'Thomas Edison', objectives: 'Make a fire resistant paper', descriptions: 'none', is_draft: true)
researcher.proposals.create!(title: 'World Peace',researcher: 'Com Pyutierre', coresearchers: 'Mahatma Gandhi', objectives: 'Attain inner peace', descriptions: 'none', is_draft: false)
researcher.proposals.create!(title: 'Portable Death Ray', researcher: 'Com Pyutierre', coresearchers: 'Nikola Tesla', objectives: 'Make killing a breeze', descriptions: 'none', is_draft: false)
researcher.proposals.create!(title: 'Quantum Computing', researcher: 'Palma Haul', coresearchers: 'Albert Einstein', objectives: 'I really dont know', descriptions: 'none', is_draft: false)
researcher.proposals.create!(title: 'Blackholes', researcher: 'Palma Haul', coresearchers: 'Stephen Hawking', objectives: 'Understanding that hole', descriptions: 'none', is_draft: false)
researcher.proposals.create!(title: 'Teleportation Ports', researcher: 'Palma Haul', coresearchers: 'Neil Degrasse Tyson', objectives: 'Faster travel', descriptions: 'none', is_draft: false)
user = User.create!(first_name: 'Palma', last_name: 'Haul', department: 'CoE', rank: 'Professor', contact_number: '9333867460', email: 'mail2@example.com', password: "password")
researcher = user.create_researcher!()
researcher.proposals.create!(title: 'Fire Resistant Paper', researcher: 'Com Pyutierre', coresearchers: 'Thomas Edison', objectives: 'Make a fire resistant paper', descriptions: 'none', is_draft: true)
researcher.proposals.create!(title: 'World Peace',researcher: 'Com Pyutierre', coresearchers: 'Mahatma Gandhi', objectives: 'Attain inner peace', descriptions: 'none', is_draft: false)
researcher.proposals.create!(title: 'Portable Death Ray', researcher: 'Com Pyutierre', coresearchers: 'Nikola Tesla', objectives: 'Make killing a breeze', descriptions: 'none', is_draft: false)
researcher.proposals.create!(title: 'Quantum Computing', researcher: 'Palma Haul', coresearchers: 'Albert Einstein', objectives: 'I really dont know', descriptions: 'none', is_draft: false)
researcher.proposals.create!(title: 'Blackholes', researcher: 'Palma Haul', coresearchers: 'Stephen Hawking', objectives: 'Understanding that hole', descriptions: 'none', is_draft: false)
researcher.proposals.create!(title: 'Teleportation Ports', researcher: 'Palma Haul', coresearchers: 'Neil Degrasse Tyson', objectives: 'Faster travel', descriptions: 'none', is_draft: false)
user = User.create!(first_name: 'Mang', last_name: 'Melchor', department: 'CE', rank: 'Instructor', contact_number: '9835583620', email: 'mail3@example.com', password: "password")
user.create_admin!()
user = User.create!(first_name: 'Romulo', last_name: 'Hall', department: 'ECE', rank: 'Instructor', contact_number: '9653778294', email: 'mail4@example.com', password: "password")
user.create_committee_member!()
user = User.create!(first_name: 'Alfred', last_name: 'Vargas', department: 'CS', rank: '5', contact_number: '9768465839', email: 'mail5@example.com', password: "password")
user.create_committee_member!()
user = User.create!(first_name: 'Alfred', last_name: 'Vargas', department: 'CS', rank: '5', contact_number: '9768465839', email: 'dean@example.com', password: "password")
user.create_dean!()
